# Generated by Django 2.2.1 on 2019-05-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0002_initial_data")]

    operations = [
        migrations.AlterModelOptions(name="event", options={"ordering": ["-datetime"]})
    ]
