# Generated by Django 2.2.1 on 2019-06-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190602_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gallery',
        ),
    ]
