# Generated by Django 2.2.2 on 2019-06-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='featured_image',
            new_name='_featured_image',
        ),
    ]
