# Generated by Django 2.2.3 on 2019-07-23 02:43

from django.db import migrations, models
from django.utils.text import slugify


def slugify_titles(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        event.slug = slugify(event.title)
        event.save()


class Migration(migrations.Migration):

    dependencies = [("events", "0010_event__qrcode")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(slugify_titles),
    ]
