# Generated by Django 2.2.1 on 2019-05-29 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Or alias you would prefer to go by.', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('artist_statement', models.TextField(help_text="Tell us about yourself and why you'd like to participate in Art/Re/Art")),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSignupWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('medium', models.CharField(help_text='Can have multiple, ex. Painting, Installation, Video', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('special_installation_needs', models.TextField(blank=True, help_text='ex. Needs to be hanging', null=True)),
                ('artist_signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='forms.ArtistSignup')),
            ],
        ),
    ]
