# Generated by Django 2.2.1 on 2019-06-05 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190601_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsignup',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
