# Generated by Django 2.2.1 on 2019-06-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("forms", "0004_artistsignup_submitted")]

    operations = [
        migrations.AlterModelOptions(
            name="artistsignup", options={"ordering": ["-submitted"]}
        )
    ]
