# Generated by Django 2.2.2 on 2019-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("forms", "0006_auto_20190622_1456")]

    operations = [
        migrations.AlterField(
            model_name="artistsignupwork",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="work", to="forms.ArtistSignupWorkImage"
            ),
        ),
        migrations.AlterField(
            model_name="artistsignupworkimage",
            name="image",
            field=models.ImageField(upload_to="artist_uploads/"),
        ),
    ]
