# Generated by Django 2.2.4 on 2019-08-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuntItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', models.PositiveSmallIntegerField(blank=True, default=100, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255, null=True)),
                ('answer_type', models.CharField(choices=[('str', 'String'), ('qr', 'QR Code'), ('int', 'Integer')], max_length=255, null=True)),
            ],
            options={
                'ordering': ['_order'],
            },
        ),
    ]
