# Generated by Django 2.2.1 on 2019-06-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("about", "0003_auto_20190528_2127")]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "about", "verbose_name_plural": "about"},
        )
    ]
