# Generated by Django 2.2.2 on 2019-06-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20190606_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdeveloper',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutfaq',
            name='is_mobile',
            field=models.BooleanField(default=True),
        ),
    ]
