# Generated by Django 2.2.2 on 2019-06-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("about", "0007_auto_20190619_2126")]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "About", "verbose_name_plural": "About"},
        )
    ]
