# Generated by Django 2.2.1 on 2019-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("artists", "0002_initial_data")]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="instagram",
            field=models.URLField(blank=True, max_length=255, null=True),
        )
    ]
