# Generated by Django 2.2.1 on 2019-06-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20190601_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
