# Generated by Django 2.2.2 on 2019-06-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artistworkimage_renameimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistworkimage',
            name='_image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
