# Generated by Django 2.2.2 on 2019-06-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("artists", "0009_auto_20190607_2256")]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Image"
            ),
        )
    ]
