# Generated by Django 2.2.2 on 2019-06-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("artists", "0013_auto_20190620_1801")]

    operations = [
        migrations.RemoveField(model_name="artistworkimage", name="is_featured")
    ]
