# Generated by Django 2.2.3 on 2019-07-23 02:34

from django.db import migrations, models
from django.utils.text import slugify


def slugify_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Artist = apps.get_model("artists", "Artist")
    for artist in Artist.objects.all():
        artist.slug = slugify(artist.name)
        artist.save()


class Migration(migrations.Migration):

    dependencies = [("artists", "0015_artist__qrcode")]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(slugify_names),
    ]
